name: Deploy SQL Data Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      fabric_url: 'g3dej5iainvulpr3gaeiaudroa-pncwescdfvhe3lvd2uueehrjre.datawarehouse.fabric.microsoft.com'
      fabric_username: 'fabrictestuser@salugandulahotmail.onmicrosoft.com'
      fabric_password: 'Poxu470761!'
      fabric_dbname: 'dwh'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Install SQLCMD
      run: |
        sudo apt-get update
        sudo apt-get install -y mssql-tools unixodbc-dev
        echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
        source ~/.bashrc

    - name: Run SQL Scripts
      run: |
        for file in ./DatabaseProjectuat/dbo/Tables/*.sql; do
          sqlcmd -S ${{ env.fabric_url }} -U ${{ env.fabric_username }} -P ${{ env.fabric_password }} -d ${{ env.fabric_dbname }} -i "$file"
        done
      env:
        DOTNET_ROOT: /usr/share/dotnet
