name: Deploy SQL Data Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install SQLPackage
      run: |
        wget https://aka.ms/sqlpackage-linux -O sqlpackage-linux.zip
        unzip -q sqlpackage-linux.zip -d sqlpackage
        sudo mv sqlpackage/sqlpackage /usr/local/bin/sqlpackage
        sudo chmod +x /usr/local/bin/sqlpackage

    - name: Deploy to Fabric Data Warehouse
      run: |
        /usr/local/bin/sqlpackage /Action:Publish /SourceFile:./DatabaseProjectuat/dbo/Tables/your.dacpac /TargetServerName:${{ secrets.fabric_url }} /TargetDatabaseName:your-database /TargetUser:${{ secrets.fabric_username }} /TargetPassword:${{ secrets.fabric_password }}
      env:
        DOTNET_ROOT: /usr/share/dotnet
