name: Deploy SQL Data Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      fabric_url: 'g3dej5iainvulpr3gaeiaudroa-pncwescdfvhe3lvd2uueehrjre.datawarehouse.fabric.microsoft.com'
      fabric_username: 'fabrictestuser@salugandulahotmail.onmicrosoft.com'
      fabric_password: 'Poxu470761!'
      fabric_dbname: 'dwh!'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Install SQLPackage
      run: |
        dotnet tool install -g microsoft.sqlpackage
        echo 'export PATH="$PATH:$HOME/.dotnet/tools"' >> $GITHUB_ENV

    - name: Deploy to Fabric Data Warehouse
      run: |
        sqlpackage /Action:Publish /SourceFile:./DatabaseProjectuat/dbo/Tables/your.dacpac /TargetServerName:${{ env.fabric_url }} /TargetDatabaseName:${{ env.fabric_dbname }} /TargetUser:${{ secrets.fabric_username }} /TargetPassword:${{ secrets.fabric_password }}
      env:
        DOTNET_ROOT: /usr/share/dotnet
