name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SQL Server
        run: |
          sudo apt-get update
          sudo apt-get install -y mssql-server

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy Tables to Fabric Warehouse
        env:
          FABRIC_CONNECTION_STRING: ${{ secrets.FABRIC_WAREHOUSE_URL }}
          FABRIC_USERNAME: ${{ secrets.FABRIC_USERNAME }}
          FABRIC_PASSWORD: ${{ secrets.FABRIC_PASSWORD }}
        run: |
          for file in $(find ./Tables -name '*.sql'); do
            sqlcmd -S ${{ env.FABRIC_CONNECTION_STRING }} -U ${{ env.FABRIC_USERNAME }} -P ${{ env.FABRIC_PASSWORD }} -d ${{ secrets.DATABASE_NAME }} -i $file
          done
